config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  resources :articles

  # routes to authenticate user - signup
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create' # post request to send completed form to the user create action
  resources :users, except: [:new] # Replaced line 10 with this. As new action already defined in line 9, dont need new route again

  get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/article.rb
class Article < ApplicationRecord
    # for ==> has-many-association
    belongs_to :user

    # for ==> many-to-many-association
    has_many :article_categories
    has_many :categories, through: :article_categories 

    #check these validations before saving article
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

# ==> Article.update_all(user_id: User.first.id)
# From the console, we can assign all articles created before adding user_id column to articles table to a user using the command above

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy] # make sure this comes below check if user has login before_action :require_login

  def index
    # @articles = Article.all
    @articles = Article.paginate(page: params[:page], per_page: 5) # pagination
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params_article)
    @article.user = current_user # current_user method is in application_controller.rb
    if @article.save
      flash[:notice] = "Article was saved successfully"
      redirect_to @article
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(params_article)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private

  def params_article
    params.require(:article).permit(:title, :description, category_ids: []) # categories_ids will store the list of categories added when creating new article
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @article
    end
  end

end

 #byebug --> use to pause program to verify values are being passed at each stage of execution
 #render plain: params[:article]  Displays the form params in plain text.

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-body rounded">
    <div class="card-header fst-italic custom-card-style">
      <% if article.user %>
        by <%= link_to article.user.username, user_path(article.user) %>
      <% end %>
    </div>

    <% if article.categories.any? %>
      <span class="mt-3"><%= render article.categories %></span>
    <% end %>
    <div class="card-body">
      <h5 class="card-title fs-2"><%= link_to article.title, article_path(article), class:"text-success text text-decoration-none " %></h5>
      <p class="card-text fs-3"><%= truncate(article.description, length: 100) %></p>
     
      <%= link_to 'View', article_path(article), class: "btn btn-outline-success fs-3" %>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-info fs-3" %>
        <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger fs-3" %>
      <% end %>
    </div>
    <div class="card-footer text-muted custom-card-style">
    <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
      edited <%= time_ago_in_words(article.updated_at) %> ago </small>
    </div>
    </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
 
  <div class="row justify-content-center">
    <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-4 bg-body rounded form-custom",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class:"col-2 col-form-label fs-3"%>
          <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded fs-3 mb-3", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Description, class:"col-2 col-form-label fs-3" %>
          <div class="col-10">
          <%= f.text_area :description, rows: 10, class: "form-control shadow rounded fs-3", placeholder: "Description of article"  %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :categories, class:"col-2 col-form-label fs-3" %>
          <div class="col-10">
          <%= f.collection_select(:category_ids, Category.all, :id, :name, {prompt: "Make your selection from the list below (Can be empty)"}, {multiple: true, size: 4, class: "form-select fs-3 shadow rounded mt-3"}) %>
          </div>
      </div>

        <div class="form-group row justify-content-center mt-5">
          <%= f.submit class:"btn btn-outline-success btn-lg form-btn-custom fs-3 shadow rounded"%>
        </div>

      <% end %>
      </div>
    <%= link_to '[ Cancel and return to article listing ]', articles_path, class:"text-info text-center" %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mb-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mb-4">Listing all articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>



<div class="text-center">
  <%= link_to 'Create new article', new_article_path, class: "btn btn-outline-info fs-3 mt-4 mb-4" %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mb-4">Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mb-4"><%= @article.title%></h1>

  <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
  <div class="card text-center shadow mb-5 bg-body rounded">
    <div class="card-header fst-italic custom-card-style">
      by <%= @article.user.username if @article.user %>
      <%= link_to gravatar_for(@article.user), user_path(@article.user) %>

      <% if @article.categories.any? %>
        <p class="mr-2"><%= render @article.categories %></p>
      <% end %>
    </div>
    <div class="card-body">
      <div class="card-text fs-3 text-start"><%= simple_format(@article.description) %></div>
     
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info fs-3" %>
        <%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-outline-danger fs-3" %>
      <% end %>
    </div>
    <div class="card-footer text-muted custom-card-style">
    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
      edited <%= time_ago_in_words(@article.updated_at) %> ago </small>
    </div>
    </div>
    </div>
  </div>


<div class="text-center">
  <%= link_to 'Create new article', new_article_path, class: "btn btn-outline-info fs-3 mt-4 mb-4" %>
</div>