config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  resources :articles

  # routes to authenticate user - signup
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create' # post request to send completed form to the user create action
  resources :users, except: [:new] # Replaced line 10 with this. As new action already defined in line 9, dont need new route again

  get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord

  # for ==> many-to-many-association
  has_many :article_categories
  has_many :articles, through: :article_categories 

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :name, uniqueness: { case_sensitive: false }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5) # pagination
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Catergory was created successfully"
      redirect_to @category
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5) # this will help grab @articles instance variable in the category show view
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated successfully"
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-success text-white fs-4 mx-2" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-4 bg-body rounded form-custom",local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class:"col-2 col-form-label fs-3"%>
          <div class="col-10">
          <%= f.text_field :name, class: "form-control shadow rounded fs-3 mb-3", placeholder: "Enter a category" %>
          </div>
        </div>

        <div class="form-group row justify-content-center mt-5">
          <%= f.submit class:"btn btn-outline-success btn-lg form-btn-custom fs-3" %>
        </div>

      <% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mb-4">Edit category name</h1>

<div class="container">
 
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'form' %>
      </div>
    <%= link_to '[ Cancel and return to category listing ]', category_path(@category), class:"text-info text-center" %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mb-4">Listing all categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
  <div class="row justify-content-md-center">
  <div class="col-4 mt-4">
  <div class="card text-center shadow mb-5 bg-body rounded">
    
    <div class="card-body">
      <h5 class="card-title fs-2"><%= link_to category.name, category_path(category), class:"text-success text text-decoration-none " %></h5>
      <p class="card-text fs-3"><%= pluralize(category.articles.count, "article") %></p>
    </div>
    <div class="card-footer text-muted custom-card-style">
    <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
      edited <%= time_ago_in_words(category.updated_at) %> ago </small>
    </div>
    </div>
    </div>
  </div>
<% end %>


<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mb-4">Create a new category</h1>

<div class="container">
 
  <div class="row justify-content-center">
    <div class="col-10">
        <%= render 'form' %>
      </div>
    <%= link_to '[ Cancel and return to category listing ]', categories_path, class:"text-info text-center" %>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mb-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
  <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info fs-3 mb-5" %>
  </div>
<% end %>

<h3 class="text-center mt-2 mb-4 fs-1">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>