config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#index'
  resources :articles

  # routes to authenticate user - signup
  get 'signup', to: 'users#new'
  #post 'users', to: 'users#create' # post request to send completed form to the user create action
  resources :users, except: [:new] # Replaced line 10 with this. As new action already defined in line 9, dont need new route again

  get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
<samll>Copyright &copy; <%= link_to "Mcdev", "https://green-blogs.herokuapp.com/", class: "footer_link text-white" %></samll>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if flash[:notice] %>
      <div class="flash-msg notice">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <%= msg %>
      </div>

    <% else %>
      <div class="flash-msg alert">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
        <%= msg %>
      </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light custom-nav-style">
  <div class="container-fluid">
  <%= link_to "GREEN BLOG", root_path, class: "navbar-brand", class: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "Create new article", new_article_path, class: "dropdown-item drop-style" %>
            <% end %>  
            <%= link_to "View articles", articles_path, class: "dropdown-item drop-style" %>        
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Create new category", new_category_path, class: "dropdown-item drop-style" %>
            <% end %>  
            <%= link_to "View categories", categories_path, class: "dropdown-item drop-style" %> 
          </ul>
        </li>
        <% if logged_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item drop-style" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item drop-style" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger drop-style", method: :delete, data: { confirm: "Are you sure?" } %> 
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
        <% else %>
          <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2 fs-3" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success fs-3" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="Site">
    <%= render "layouts/navbar" %>
    <main class="Site-content">
    <div class="page-container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
      
   
   
    </main>
    <%= render 'layouts/footer' %> 
  </body>
</html>